import React, { useState, useEffect } from 'react';
import type {Supplier}   from '../data/suppliers';
import './supplierFormModal.css';

interface SupplierFormModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (supplier: Omit<Supplier, 'id'> | Supplier) => void;
  supplier?: Supplier | null; // Optional: for editing an existing supplier
}

export default function SupplierFormModal({ isOpen, onClose, onSave, supplier }: SupplierFormModalProps) {
  const [name, setName] = useState('');
  const [contactName, setContactName] = useState('');
  const [phone, setPhone] = useState('');
  const [email, setEmail] = useState('');
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (isOpen) {
      if (supplier) {
        // Populate form for editing
        setName(supplier.name);
        setContactName(supplier.contact_name || '');
        setPhone(supplier.phone || '');
        setEmail(supplier.email || '');
      } else {
        // Reset form for adding
        setName('');
        setContactName('');
        setPhone('');
        setEmail('');
      }
      setError(null);
    }
  }, [isOpen, supplier]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    if (!name.trim()) {
      setError('El nombre del proveedor es obligatorio.');
      return;
    }

    const supplierData: Omit<Supplier, 'id'> = {
      name,
      contact_name: contactName,
      phone,
      email,
    };

    if (supplier) {
        // If editing, include the ID
        onSave({ ...supplierData, id: supplier.id });
    } else {
        // If adding, ID will be generated by Supabase
        onSave(supplierData);
    }
    
    onClose(); // Close modal after saving
  };

  if (!isOpen) return null;

  return (
    <div className="supplier-modal-overlay">
      <div className="supplier-modal-content">
        <div className="supplier-modal-header">
          <h2>{supplier ? 'Editar Proveedor' : 'Agregar Proveedor'}</h2>
          <button onClick={onClose} className="supplier-modal-close-btn">&times;</button>
        </div>
        
        <form onSubmit={handleSubmit}>
          {error && <p className="supplier-error-message">{error}</p>}
          
          <div className="supplier-form-group">
            <label htmlFor="name">Nombre del Proveedor</label>
            <input
              type="text"
              id="name"
              value={name}
              onChange={e => setName(e.target.value)}
              required
            />
          </div>
          
          <div className="supplier-form-group">
            <label htmlFor="contactName">Persona de Contacto</label>
            <input
              type="text"
              id="contactName"
              value={contactName}
              onChange={e => setContactName(e.target.value)}
            />
          </div>
          
          <div className="supplier-form-group">
            <label htmlFor="phone">Teléfono</label>
            <input
              type="tel"
              id="phone"
              value={phone}
              onChange={e => setPhone(e.target.value)}
            />
          </div>
          
          <div className="supplier-form-group">
            <label htmlFor="email">Email</label>
            <input
              type="email"
              id="email"
              value={email}
              onChange={e => setEmail(e.target.value)}
            />
          </div>

          <div className="supplier-modal-footer">
            <button type="button" onClick={onClose} className="supplier-modal-btn-cancel">Cancelar</button>
            <button type="submit" className="supplier-modal-btn-save">Guardar</button>
          </div>
        </form>
      </div>
    </div>
  );
}
